#!/usr/bin/env python3
"""Create Localizable.strings files for all iOS locales in WebImagePicker package."""
import os

RESOURCES_DIR = "/Users/nathanfennel/Documents/GitHub/Bratify/Packages/WebImagePicker/Sources/WebImagePicker/Resources"

# English source strings with keys
EN_STRINGS = {
    "webimage.a11y.imageFromWeb": "Image from web",
    "webimage.a11y.selectionSummaryFormat": "%lld of %lld selected",
    "webimage.a11y.imageSearchField": "Search images",
    "webimage.a11y.imageSearchFieldHint": "Filters the list by alt text, title, or image address. Add format:png or format:webp to narrow by file type.",
    "webimage.cancel": "Cancel",
    "webimage.changeURL": "Change URL",
    "webimage.done": "Done",
    "webimage.error.downloadFailed": "Could not download an image.",
    "webimage.error.unsupportedImageType": "This image type is not allowed.",
    "webimage.error.imageDecodeFailed": "Downloaded data could not be decoded as an image.",
    "webimage.error.enterValidURL": "Enter a valid URL.",
    "webimage.error.extractionFailed": "Could not read images from this page.",
    "webimage.error.generic": "Something went wrong.",
    "webimage.error.htmlDecodingFailed": "Could not read the page text.",
    "webimage.error.htmlTooLarge": "The page is too large to load safely.",
    "webimage.error.imageTooLarge": "An image was too large to download.",
    "webimage.error.invalidHTTPResponse": "The server did not return the page.",
    "webimage.error.invalidURL": "That URL is not allowed or invalid.",
    "webimage.error.noImagesFound": "No images were found on this page.",
    "webimage.error.schemeNotAllowed": "This URL scheme is not allowed.",
    "webimage.error.httpNotAllowed": "This URL uses HTTP. Only HTTPS is allowed. Change the URL to HTTPS or ask the app developer to allow HTTP in WebImagePicker configuration and App Transport Security.",
    "webimage.skippedHTTPImagesNoticeFormat": "Some images were skipped because they use HTTP (%lld). Use HTTPS image URLs, or ask the app developer to allow HTTP in WebImagePicker configuration and App Transport Security.",
    "webimage.loadPage": "Load page",
    "webimage.loading": "Loading",
    "webimage.navTitle": "Web images",
    "webimage.selectionSummaryFormat": "%lld of %lld selected",
    "webimage.urlEntryFooter": "Paste a page URL. Images from the HTML response are shown (JavaScript-only images may be missing).",
    "webimage.urlPlaceholder": "https://example.com",
    "webimage.additionalPagesSection": "Additional pages",
    "webimage.additionalPagesFooter": "Optional: add more page URLs to combine images from several pages in one grid. Your host app can also set WebImagePickerConfiguration.additionalPageURLs.",
    "webimage.addPage": "Add page",
    "webimage.extraPagePlaceholder": "https://another.example.com",
    "webimage.error.allPagesFailed": "Could not load images from any of the pages.",
    "webimage.partialPageFailuresFormat": "%lld page(s) could not be loaded. Images from the other pages are shown.",
    "webimage.searchPlaceholder": "Search by alt, title, or URL",
}

# Translations for each locale
# Format: locale -> {key -> value}
TRANSLATIONS = {
    "af": {
        "webimage.a11y.imageFromWeb": "Prent van die web",
        "webimage.a11y.selectionSummaryFormat": "%1$lld van %2$lld gekies",
        "webimage.a11y.imageSearchField": "Soek prente",
        "webimage.a11y.imageSearchFieldHint": "Filtreer die lys op alt-teks, titel of prentadres. Voeg format:png of format:webp by om op lêertipe te filtreer.",
        "webimage.cancel": "Kanselleer",
        "webimage.changeURL": "Verander URL",
        "webimage.done": "Klaar",
        "webimage.error.downloadFailed": "Kon nie 'n prent aflaai nie.",
        "webimage.error.unsupportedImageType": "Hierdie prenttipe is nie toegelaat nie.",
        "webimage.error.imageDecodeFailed": "Afgelaaide data kon nie as prent ontsyfer word nie.",
        "webimage.error.enterValidURL": "Voer 'n geldige URL in.",
        "webimage.error.extractionFailed": "Kon nie prente van hierdie bladsy lees nie.",
        "webimage.error.generic": "Iets het verkeerd gegaan.",
        "webimage.error.htmlDecodingFailed": "Kon nie die bladsy teks lees nie.",
        "webimage.error.htmlTooLarge": "Die bladsy is te groot om veilig te laai.",
        "webimage.error.imageTooLarge": "'n Prent was te groot om af te laai.",
        "webimage.error.invalidHTTPResponse": "Die bediener het nie die bladsy teruggestuur nie.",
        "webimage.error.invalidURL": "Daardie URL is nie toegelaat of ongeldig nie.",
        "webimage.error.noImagesFound": "Geen prente is op hierdie bladsy gevind nie.",
        "webimage.error.schemeNotAllowed": "Hierdie URL-skema is nie toegelaat nie.",
        "webimage.error.httpNotAllowed": "Hierdie URL gebruik HTTP. Slegs HTTPS is toegelaat. Verander die URL na HTTPS of vra die app-ontwikkelaar om HTTP in WebImagePicker-konfigurasie toe te laat.",
        "webimage.skippedHTTPImagesNoticeFormat": "Sommige prente is oorgeslaan omdat hulle HTTP gebruik (%lld). Gebruik HTTPS-prent-URL's of vra die ontwikkelaar om HTTP toe te laat.",
        "webimage.loadPage": "Laai bladsy",
        "webimage.loading": "Laai",
        "webimage.navTitle": "Webprente",
        "webimage.selectionSummaryFormat": "%1$lld van %2$lld gekies",
        "webimage.urlEntryFooter": "Plak 'n bladsy-URL. Prente uit die HTML-reaksie word gewys (JavaScript-slegs prente kan ontbreek).",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Addisionele bladsye",
        "webimage.additionalPagesFooter": "Opsioneel: voeg meer bladsy-URL's by om prente van verskeie bladsye saam te voeg.",
        "webimage.addPage": "Voeg bladsy by",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Kon nie prente van enige bladsy laai nie.",
        "webimage.partialPageFailuresFormat": "%lld bladsy(e) kon nie gelaai word nie. Prente van die ander bladsye word gewys.",
        "webimage.searchPlaceholder": "Soek op alt, titel of URL",
    },
    "ar": {
        "webimage.a11y.imageFromWeb": "صورة من الويب",
        "webimage.a11y.selectionSummaryFormat": "%1$lld من %2$lld محددة",
        "webimage.a11y.imageSearchField": "بحث عن الصور",
        "webimage.a11y.imageSearchFieldHint": "يصفي القائمة حسب النص البديل أو العنوان أو عنوان الصورة. أضف format:png أو format:webp للتصفية حسب نوع الملف.",
        "webimage.cancel": "إلغاء",
        "webimage.changeURL": "تغيير الرابط",
        "webimage.done": "تم",
        "webimage.error.downloadFailed": "تعذر تنزيل الصورة.",
        "webimage.error.unsupportedImageType": "نوع الصورة هذا غير مسموح به.",
        "webimage.error.imageDecodeFailed": "تعذر فك ترميز البيانات المنزلة كصورة.",
        "webimage.error.enterValidURL": "أدخل رابطاً صالحاً.",
        "webimage.error.extractionFailed": "تعذر قراءة الصور من هذه الصفحة.",
        "webimage.error.generic": "حدث خطأ ما.",
        "webimage.error.htmlDecodingFailed": "تعذر قراءة نص الصفحة.",
        "webimage.error.htmlTooLarge": "الصفحة كبيرة جداً لتحميلها بأمان.",
        "webimage.error.imageTooLarge": "كانت الصورة كبيرة جداً للتنزيل.",
        "webimage.error.invalidHTTPResponse": "لم يعد الخادم الصفحة.",
        "webimage.error.invalidURL": "هذا الرابط غير مسموح به أو غير صالح.",
        "webimage.error.noImagesFound": "لم يتم العثور على صور في هذه الصفحة.",
        "webimage.error.schemeNotAllowed": "مخطط URL هذا غير مسموح به.",
        "webimage.error.httpNotAllowed": "يستخدم هذا الرابط HTTP. يُسمح بـ HTTPS فقط. غير الرابط إلى HTTPS أو اطلب من مطوّر التطبيق السماح بـ HTTP.",
        "webimage.skippedHTTPImagesNoticeFormat": "تم تخطي بعض الصور لأنها تستخدم HTTP (%lld). استخدم روابط HTTPS أو اطلب من المطوّر السماح بـ HTTP.",
        "webimage.loadPage": "تحميل الصفحة",
        "webimage.loading": "جارٍ التحميل",
        "webimage.navTitle": "صور الويب",
        "webimage.selectionSummaryFormat": "%1$lld من %2$lld محددة",
        "webimage.urlEntryFooter": "الصق رابط الصفحة. تظهر الصور من استجابة HTML (قد تكون الصور التي تعتمد على JavaScript مفقودة).",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "صفحات إضافية",
        "webimage.additionalPagesFooter": "اختياري: أضف روابط صفحات أخرى لدمج الصور من عدة صفحات.",
        "webimage.addPage": "إضافة صفحة",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "تعذر تحميل الصور من أي صفحة.",
        "webimage.partialPageFailuresFormat": "تعذر تحميل %lld صفحة. تظهر صور الصفحات الأخرى.",
        "webimage.searchPlaceholder": "البحث حسب النص البديل أو العنوان أو الرابط",
    },
    "de": {
        "webimage.a11y.imageFromWeb": "Bild aus dem Web",
        "webimage.a11y.selectionSummaryFormat": "%1$lld von %2$lld ausgewählt",
        "webimage.a11y.imageSearchField": "Bilder suchen",
        "webimage.a11y.imageSearchFieldHint": "Filtert die Liste nach Alt-Text, Titel oder Bildadresse. Füge format:png oder format:webp hinzu, um nach Dateityp zu filtern.",
        "webimage.cancel": "Abbrechen",
        "webimage.changeURL": "URL ändern",
        "webimage.done": "Fertig",
        "webimage.error.downloadFailed": "Ein Bild konnte nicht heruntergeladen werden.",
        "webimage.error.unsupportedImageType": "Dieser Bildtyp ist nicht erlaubt.",
        "webimage.error.imageDecodeFailed": "Die heruntergeladenen Daten konnten nicht als Bild dekodiert werden.",
        "webimage.error.enterValidURL": "Gib eine gültige URL ein.",
        "webimage.error.extractionFailed": "Bilder konnten von dieser Seite nicht gelesen werden.",
        "webimage.error.generic": "Es ist ein Fehler aufgetreten.",
        "webimage.error.htmlDecodingFailed": "Der Seitentext konnte nicht gelesen werden.",
        "webimage.error.htmlTooLarge": "Die Seite ist zu groß zum sicheren Laden.",
        "webimage.error.imageTooLarge": "Ein Bild war zu groß zum Herunterladen.",
        "webimage.error.invalidHTTPResponse": "Der Server hat die Seite nicht zurückgegeben.",
        "webimage.error.invalidURL": "Diese URL ist nicht erlaubt oder ungültig.",
        "webimage.error.noImagesFound": "Auf dieser Seite wurden keine Bilder gefunden.",
        "webimage.error.schemeNotAllowed": "Dieses URL-Schema ist nicht erlaubt.",
        "webimage.error.httpNotAllowed": "Diese URL verwendet HTTP. Nur HTTPS ist erlaubt. Ändere die URL zu HTTPS oder bitte den App-Entwickler, HTTP zu erlauben.",
        "webimage.skippedHTTPImagesNoticeFormat": "Einige Bilder wurden übersprungen, weil sie HTTP verwenden (%lld). Verwende HTTPS-URLs oder bitte den Entwickler, HTTP zu erlauben.",
        "webimage.loadPage": "Seite laden",
        "webimage.loading": "Wird geladen",
        "webimage.navTitle": "Web-Bilder",
        "webimage.selectionSummaryFormat": "%1$lld von %2$lld ausgewählt",
        "webimage.urlEntryFooter": "Seiten-URL einfügen. Bilder aus der HTML-Antwort werden angezeigt (JavaScript-only-Bilder können fehlen).",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Weitere Seiten",
        "webimage.additionalPagesFooter": "Optional: Weitere Seiten-URLs hinzufügen, um Bilder aus mehreren Seiten zu kombinieren.",
        "webimage.addPage": "Seite hinzufügen",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Bilder konnten von keiner Seite geladen werden.",
        "webimage.partialPageFailuresFormat": "%lld Seite(n) konnten nicht geladen werden. Bilder der anderen Seiten werden angezeigt.",
        "webimage.searchPlaceholder": "Nach Alt-Text, Titel oder URL suchen",
    },
    "fr": {
        "webimage.a11y.imageFromWeb": "Image du web",
        "webimage.a11y.selectionSummaryFormat": "%1$lld sur %2$lld sélectionnée(s)",
        "webimage.a11y.imageSearchField": "Rechercher des images",
        "webimage.a11y.imageSearchFieldHint": "Filtre la liste par texte alt, titre ou adresse de l'image. Ajoutez format:png ou format:webp pour filtrer par type de fichier.",
        "webimage.cancel": "Annuler",
        "webimage.changeURL": "Modifier l'URL",
        "webimage.done": "Terminé",
        "webimage.error.downloadFailed": "Impossible de télécharger une image.",
        "webimage.error.unsupportedImageType": "Ce type d'image n'est pas autorisé.",
        "webimage.error.imageDecodeFailed": "Les données téléchargées n'ont pas pu être décodées comme image.",
        "webimage.error.enterValidURL": "Entrez une URL valide.",
        "webimage.error.extractionFailed": "Impossible de lire les images de cette page.",
        "webimage.error.generic": "Une erreur s'est produite.",
        "webimage.error.htmlDecodingFailed": "Impossible de lire le texte de la page.",
        "webimage.error.htmlTooLarge": "La page est trop grande pour être chargée en toute sécurité.",
        "webimage.error.imageTooLarge": "Une image était trop grande pour être téléchargée.",
        "webimage.error.invalidHTTPResponse": "Le serveur n'a pas renvoyé la page.",
        "webimage.error.invalidURL": "Cette URL n'est pas autorisée ou est invalide.",
        "webimage.error.noImagesFound": "Aucune image trouvée sur cette page.",
        "webimage.error.schemeNotAllowed": "Ce schéma d'URL n'est pas autorisé.",
        "webimage.error.httpNotAllowed": "Cette URL utilise HTTP. Seul HTTPS est autorisé. Modifiez l'URL en HTTPS ou demandez au développeur d'autoriser HTTP.",
        "webimage.skippedHTTPImagesNoticeFormat": "Certaines images ont été ignorées car elles utilisent HTTP (%lld). Utilisez des URL HTTPS ou demandez au développeur d'autoriser HTTP.",
        "webimage.loadPage": "Charger la page",
        "webimage.loading": "Chargement",
        "webimage.navTitle": "Images web",
        "webimage.selectionSummaryFormat": "%1$lld sur %2$lld sélectionnée(s)",
        "webimage.urlEntryFooter": "Collez l'URL d'une page. Les images de la réponse HTML s'affichent (les images JavaScript uniquement peuvent manquer).",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Pages supplémentaires",
        "webimage.additionalPagesFooter": "Optionnel : ajoutez d'autres URL de pages pour combiner les images de plusieurs pages.",
        "webimage.addPage": "Ajouter une page",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Impossible de charger des images depuis une quelconque page.",
        "webimage.partialPageFailuresFormat": "%lld page(s) n'ont pas pu être chargées. Les images des autres pages sont affichées.",
        "webimage.searchPlaceholder": "Rechercher par alt, titre ou URL",
    },
    "ja": {
        "webimage.a11y.imageFromWeb": "ウェブの画像",
        "webimage.a11y.selectionSummaryFormat": "%2$lld 件中 %1$lld 件を選択",
        "webimage.a11y.imageSearchField": "画像を検索",
        "webimage.a11y.imageSearchFieldHint": "alt テキスト、タイトル、または画像アドレスでリストを絞り込みます。format:png または format:webp を追加してファイル形式で絞り込めます。",
        "webimage.cancel": "キャンセル",
        "webimage.changeURL": "URL を変更",
        "webimage.done": "完了",
        "webimage.error.downloadFailed": "画像をダウンロードできませんでした。",
        "webimage.error.unsupportedImageType": "この画像形式は許可されていません。",
        "webimage.error.imageDecodeFailed": "ダウンロードされたデータを画像としてデコードできませんでした。",
        "webimage.error.enterValidURL": "有効な URL を入力してください。",
        "webimage.error.extractionFailed": "このページから画像を読み取れませんでした。",
        "webimage.error.generic": "問題が発生しました。",
        "webimage.error.htmlDecodingFailed": "ページのテキストを読み取れませんでした。",
        "webimage.error.htmlTooLarge": "ページが大きすぎて安全に読み込めません。",
        "webimage.error.imageTooLarge": "画像が大きすぎてダウンロードできませんでした。",
        "webimage.error.invalidHTTPResponse": "サーバーがページを返しませんでした。",
        "webimage.error.invalidURL": "その URL は許可されていないか無効です。",
        "webimage.error.noImagesFound": "このページに画像は見つかりませんでした。",
        "webimage.error.schemeNotAllowed": "この URL スキームは許可されていません。",
        "webimage.error.httpNotAllowed": "この URL は HTTP を使用しています。HTTPS のみ許可されています。URL を HTTPS に変更するか、アプリ開発者に HTTP の許可を依頼してください。",
        "webimage.skippedHTTPImagesNoticeFormat": "HTTP を使用している画像 (%lld 件) がスキップされました。HTTPS の画像 URL を使用するか、開発者に HTTP の許可を依頼してください。",
        "webimage.loadPage": "ページを読み込む",
        "webimage.loading": "読み込み中",
        "webimage.navTitle": "ウェブ画像",
        "webimage.selectionSummaryFormat": "%2$lld 件中 %1$lld 件を選択",
        "webimage.urlEntryFooter": "ページの URL を貼り付けてください。HTML レスポンスの画像が表示されます（JavaScript 専用の画像は表示されない場合があります）。",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "追加ページ",
        "webimage.additionalPagesFooter": "オプション: 複数ページの画像をまとめて表示するために追加の URL を入力してください。",
        "webimage.addPage": "ページを追加",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "どのページからも画像を読み込めませんでした。",
        "webimage.partialPageFailuresFormat": "%lld ページを読み込めませんでした。他のページの画像が表示されています。",
        "webimage.searchPlaceholder": "alt、タイトル、または URL で検索",
    },
    "ko": {
        "webimage.a11y.imageFromWeb": "웹의 이미지",
        "webimage.a11y.selectionSummaryFormat": "%2$lld개 중 %1$lld개 선택됨",
        "webimage.a11y.imageSearchField": "이미지 검색",
        "webimage.a11y.imageSearchFieldHint": "alt 텍스트, 제목 또는 이미지 주소로 목록을 필터링합니다. format:png 또는 format:webp를 추가하여 파일 형식으로 좁힐 수 있습니다.",
        "webimage.cancel": "취소",
        "webimage.changeURL": "URL 변경",
        "webimage.done": "완료",
        "webimage.error.downloadFailed": "이미지를 다운로드할 수 없습니다.",
        "webimage.error.unsupportedImageType": "이 이미지 유형은 허용되지 않습니다.",
        "webimage.error.imageDecodeFailed": "다운로드된 데이터를 이미지로 디코딩할 수 없습니다.",
        "webimage.error.enterValidURL": "유효한 URL을 입력하세요.",
        "webimage.error.extractionFailed": "이 페이지에서 이미지를 읽을 수 없습니다.",
        "webimage.error.generic": "오류가 발생했습니다.",
        "webimage.error.htmlDecodingFailed": "페이지 텍스트를 읽을 수 없습니다.",
        "webimage.error.htmlTooLarge": "페이지가 너무 커서 안전하게 로드할 수 없습니다.",
        "webimage.error.imageTooLarge": "이미지가 너무 커서 다운로드할 수 없습니다.",
        "webimage.error.invalidHTTPResponse": "서버가 페이지를 반환하지 않았습니다.",
        "webimage.error.invalidURL": "해당 URL은 허용되지 않거나 유효하지 않습니다.",
        "webimage.error.noImagesFound": "이 페이지에서 이미지를 찾을 수 없습니다.",
        "webimage.error.schemeNotAllowed": "이 URL 스킴은 허용되지 않습니다.",
        "webimage.error.httpNotAllowed": "이 URL은 HTTP를 사용합니다. HTTPS만 허용됩니다. URL을 HTTPS로 변경하거나 앱 개발자에게 HTTP 허용을 요청하세요.",
        "webimage.skippedHTTPImagesNoticeFormat": "HTTP를 사용하는 이미지 (%lld개)가 건너뛰어졌습니다. HTTPS 이미지 URL을 사용하거나 개발자에게 HTTP 허용을 요청하세요.",
        "webimage.loadPage": "페이지 로드",
        "webimage.loading": "로딩 중",
        "webimage.navTitle": "웹 이미지",
        "webimage.selectionSummaryFormat": "%2$lld개 중 %1$lld개 선택됨",
        "webimage.urlEntryFooter": "페이지 URL을 붙여넣으세요. HTML 응답의 이미지가 표시됩니다(JavaScript 전용 이미지는 없을 수 있습니다).",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "추가 페이지",
        "webimage.additionalPagesFooter": "선택 사항: 여러 페이지의 이미지를 합치려면 추가 URL을 입력하세요.",
        "webimage.addPage": "페이지 추가",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "어느 페이지에서도 이미지를 로드할 수 없습니다.",
        "webimage.partialPageFailuresFormat": "%lld개 페이지를 로드할 수 없습니다. 다른 페이지의 이미지가 표시됩니다.",
        "webimage.searchPlaceholder": "alt, 제목 또는 URL로 검색",
    },
    "zh-Hans": {
        "webimage.a11y.imageFromWeb": "来自网络的图片",
        "webimage.a11y.selectionSummaryFormat": "已选择 %1$lld 个，共 %2$lld 个",
        "webimage.a11y.imageSearchField": "搜索图片",
        "webimage.a11y.imageSearchFieldHint": "按替代文本、标题或图片地址过滤列表。添加 format:png 或 format:webp 按文件类型筛选。",
        "webimage.cancel": "取消",
        "webimage.changeURL": "更改 URL",
        "webimage.done": "完成",
        "webimage.error.downloadFailed": "无法下载图片。",
        "webimage.error.unsupportedImageType": "此图片类型不被允许。",
        "webimage.error.imageDecodeFailed": "下载的数据无法解码为图片。",
        "webimage.error.enterValidURL": "请输入有效的 URL。",
        "webimage.error.extractionFailed": "无法从此页面读取图片。",
        "webimage.error.generic": "出现了问题。",
        "webimage.error.htmlDecodingFailed": "无法读取页面文本。",
        "webimage.error.htmlTooLarge": "页面太大，无法安全加载。",
        "webimage.error.imageTooLarge": "图片太大，无法下载。",
        "webimage.error.invalidHTTPResponse": "服务器未返回页面。",
        "webimage.error.invalidURL": "该 URL 不被允许或无效。",
        "webimage.error.noImagesFound": "此页面上未找到图片。",
        "webimage.error.schemeNotAllowed": "此 URL 方案不被允许。",
        "webimage.error.httpNotAllowed": "此 URL 使用 HTTP。仅允许 HTTPS。请将 URL 改为 HTTPS，或请求应用开发者在 WebImagePicker 配置中允许 HTTP。",
        "webimage.skippedHTTPImagesNoticeFormat": "已跳过 %lld 个使用 HTTP 的图片。请使用 HTTPS 图片 URL，或请求开发者允许 HTTP。",
        "webimage.loadPage": "加载页面",
        "webimage.loading": "加载中",
        "webimage.navTitle": "网络图片",
        "webimage.selectionSummaryFormat": "已选择 %1$lld 个，共 %2$lld 个",
        "webimage.urlEntryFooter": "粘贴页面 URL。显示 HTML 响应中的图片（仅 JavaScript 图片可能缺失）。",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "附加页面",
        "webimage.additionalPagesFooter": "可选：添加更多页面 URL 以合并多个页面的图片。",
        "webimage.addPage": "添加页面",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "无法从任何页面加载图片。",
        "webimage.partialPageFailuresFormat": "%lld 个页面无法加载。显示其他页面的图片。",
        "webimage.searchPlaceholder": "按替代文本、标题或 URL 搜索",
    },
    "zh-Hant": {
        "webimage.a11y.imageFromWeb": "來自網絡的圖片",
        "webimage.a11y.selectionSummaryFormat": "已選擇 %1$lld 個，共 %2$lld 個",
        "webimage.a11y.imageSearchField": "搜尋圖片",
        "webimage.a11y.imageSearchFieldHint": "依替代文字、標題或圖片位址篩選清單。新增 format:png 或 format:webp 以依檔案類型篩選。",
        "webimage.cancel": "取消",
        "webimage.changeURL": "更改 URL",
        "webimage.done": "完成",
        "webimage.error.downloadFailed": "無法下載圖片。",
        "webimage.error.unsupportedImageType": "此圖片類型不被允許。",
        "webimage.error.imageDecodeFailed": "下載的資料無法解碼為圖片。",
        "webimage.error.enterValidURL": "請輸入有效的 URL。",
        "webimage.error.extractionFailed": "無法從此頁面讀取圖片。",
        "webimage.error.generic": "發生了問題。",
        "webimage.error.htmlDecodingFailed": "無法讀取頁面文字。",
        "webimage.error.htmlTooLarge": "頁面太大，無法安全載入。",
        "webimage.error.imageTooLarge": "圖片太大，無法下載。",
        "webimage.error.invalidHTTPResponse": "伺服器未回傳頁面。",
        "webimage.error.invalidURL": "該 URL 不被允許或無效。",
        "webimage.error.noImagesFound": "此頁面上未找到圖片。",
        "webimage.error.schemeNotAllowed": "此 URL 方案不被允許。",
        "webimage.error.httpNotAllowed": "此 URL 使用 HTTP。僅允許 HTTPS。請將 URL 改為 HTTPS，或請應用程式開發者允許 HTTP。",
        "webimage.skippedHTTPImagesNoticeFormat": "已略過 %lld 個使用 HTTP 的圖片。請使用 HTTPS 圖片 URL，或請開發者允許 HTTP。",
        "webimage.loadPage": "載入頁面",
        "webimage.loading": "載入中",
        "webimage.navTitle": "網絡圖片",
        "webimage.selectionSummaryFormat": "已選擇 %1$lld 個，共 %2$lld 個",
        "webimage.urlEntryFooter": "貼上頁面 URL。顯示 HTML 回應中的圖片（僅 JavaScript 圖片可能缺失）。",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "附加頁面",
        "webimage.additionalPagesFooter": "可選：新增更多頁面 URL 以合併多個頁面的圖片。",
        "webimage.addPage": "新增頁面",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "無法從任何頁面載入圖片。",
        "webimage.partialPageFailuresFormat": "%lld 個頁面無法載入。顯示其他頁面的圖片。",
        "webimage.searchPlaceholder": "依替代文字、標題或 URL 搜尋",
    },
    "zh-HK": {
        "webimage.a11y.imageFromWeb": "來自網頁的圖片",
        "webimage.a11y.selectionSummaryFormat": "已選擇 %1$lld 個，共 %2$lld 個",
        "webimage.a11y.imageSearchField": "搜尋圖片",
        "webimage.a11y.imageSearchFieldHint": "依替代文字、標題或圖片位址篩選清單。新增 format:png 或 format:webp 以依檔案類型篩選。",
        "webimage.cancel": "取消",
        "webimage.changeURL": "更改 URL",
        "webimage.done": "完成",
        "webimage.error.downloadFailed": "無法下載圖片。",
        "webimage.error.unsupportedImageType": "此圖片類型不被允許。",
        "webimage.error.imageDecodeFailed": "下載的資料無法解碼為圖片。",
        "webimage.error.enterValidURL": "請輸入有效的 URL。",
        "webimage.error.extractionFailed": "無法從此頁面讀取圖片。",
        "webimage.error.generic": "出現了問題。",
        "webimage.error.htmlDecodingFailed": "無法讀取頁面文字。",
        "webimage.error.htmlTooLarge": "頁面太大，無法安全載入。",
        "webimage.error.imageTooLarge": "圖片太大，無法下載。",
        "webimage.error.invalidHTTPResponse": "伺服器未回傳頁面。",
        "webimage.error.invalidURL": "該 URL 不被允許或無效。",
        "webimage.error.noImagesFound": "此頁面上未找到圖片。",
        "webimage.error.schemeNotAllowed": "此 URL 方案不被允許。",
        "webimage.error.httpNotAllowed": "此 URL 使用 HTTP。僅允許 HTTPS。請將 URL 改為 HTTPS，或請應用程式開發者允許 HTTP。",
        "webimage.skippedHTTPImagesNoticeFormat": "已略過 %lld 個使用 HTTP 的圖片。請使用 HTTPS 圖片 URL，或請開發者允許 HTTP。",
        "webimage.loadPage": "載入頁面",
        "webimage.loading": "載入中",
        "webimage.navTitle": "網頁圖片",
        "webimage.selectionSummaryFormat": "已選擇 %1$lld 個，共 %2$lld 個",
        "webimage.urlEntryFooter": "貼上頁面 URL。顯示 HTML 回應中的圖片（僅 JavaScript 圖片可能缺失）。",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "附加頁面",
        "webimage.additionalPagesFooter": "可選：新增更多頁面 URL 以合併多個頁面的圖片。",
        "webimage.addPage": "新增頁面",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "無法從任何頁面載入圖片。",
        "webimage.partialPageFailuresFormat": "%lld 個頁面無法載入。顯示其他頁面的圖片。",
        "webimage.searchPlaceholder": "依替代文字、標題或 URL 搜尋",
    },
    "pt-BR": {
        "webimage.a11y.imageFromWeb": "Imagem da web",
        "webimage.a11y.selectionSummaryFormat": "%1$lld de %2$lld selecionadas",
        "webimage.a11y.imageSearchField": "Pesquisar imagens",
        "webimage.a11y.imageSearchFieldHint": "Filtra a lista por texto alt, título ou endereço de imagem. Adicione format:png ou format:webp para filtrar por tipo de arquivo.",
        "webimage.cancel": "Cancelar",
        "webimage.changeURL": "Alterar URL",
        "webimage.done": "Concluído",
        "webimage.error.downloadFailed": "Não foi possível baixar uma imagem.",
        "webimage.error.unsupportedImageType": "Este tipo de imagem não é permitido.",
        "webimage.error.imageDecodeFailed": "Os dados baixados não puderam ser decodificados como imagem.",
        "webimage.error.enterValidURL": "Digite uma URL válida.",
        "webimage.error.extractionFailed": "Não foi possível ler imagens desta página.",
        "webimage.error.generic": "Algo deu errado.",
        "webimage.error.htmlDecodingFailed": "Não foi possível ler o texto da página.",
        "webimage.error.htmlTooLarge": "A página é muito grande para carregar com segurança.",
        "webimage.error.imageTooLarge": "Uma imagem era muito grande para baixar.",
        "webimage.error.invalidHTTPResponse": "O servidor não retornou a página.",
        "webimage.error.invalidURL": "Essa URL não é permitida ou é inválida.",
        "webimage.error.noImagesFound": "Nenhuma imagem foi encontrada nesta página.",
        "webimage.error.schemeNotAllowed": "Este esquema de URL não é permitido.",
        "webimage.error.httpNotAllowed": "Esta URL usa HTTP. Somente HTTPS é permitido. Altere a URL para HTTPS ou peça ao desenvolvedor para permitir HTTP.",
        "webimage.skippedHTTPImagesNoticeFormat": "Algumas imagens foram ignoradas porque usam HTTP (%lld). Use URLs HTTPS ou peça ao desenvolvedor para permitir HTTP.",
        "webimage.loadPage": "Carregar página",
        "webimage.loading": "Carregando",
        "webimage.navTitle": "Imagens web",
        "webimage.selectionSummaryFormat": "%1$lld de %2$lld selecionadas",
        "webimage.urlEntryFooter": "Cole uma URL de página. As imagens da resposta HTML são exibidas (imagens somente JavaScript podem estar faltando).",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Páginas adicionais",
        "webimage.additionalPagesFooter": "Opcional: adicione mais URLs de páginas para combinar imagens de várias páginas.",
        "webimage.addPage": "Adicionar página",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Não foi possível carregar imagens de nenhuma página.",
        "webimage.partialPageFailuresFormat": "%lld página(s) não pôde(ram) ser carregada(s). Imagens das outras páginas são exibidas.",
        "webimage.searchPlaceholder": "Pesquisar por alt, título ou URL",
    },
    "it": {
        "webimage.a11y.imageFromWeb": "Immagine dal web",
        "webimage.a11y.selectionSummaryFormat": "%1$lld di %2$lld selezionate",
        "webimage.a11y.imageSearchField": "Cerca immagini",
        "webimage.a11y.imageSearchFieldHint": "Filtra l'elenco per testo alt, titolo o indirizzo immagine. Aggiungi format:png o format:webp per filtrare per tipo di file.",
        "webimage.cancel": "Annulla",
        "webimage.changeURL": "Cambia URL",
        "webimage.done": "Fine",
        "webimage.error.downloadFailed": "Impossibile scaricare un'immagine.",
        "webimage.error.unsupportedImageType": "Questo tipo di immagine non è consentito.",
        "webimage.error.imageDecodeFailed": "I dati scaricati non possono essere decodificati come immagine.",
        "webimage.error.enterValidURL": "Inserisci un URL valido.",
        "webimage.error.extractionFailed": "Impossibile leggere le immagini da questa pagina.",
        "webimage.error.generic": "Qualcosa è andato storto.",
        "webimage.error.htmlDecodingFailed": "Impossibile leggere il testo della pagina.",
        "webimage.error.htmlTooLarge": "La pagina è troppo grande per essere caricata in sicurezza.",
        "webimage.error.imageTooLarge": "Un'immagine era troppo grande per essere scaricata.",
        "webimage.error.invalidHTTPResponse": "Il server non ha restituito la pagina.",
        "webimage.error.invalidURL": "Quell'URL non è consentito o non è valido.",
        "webimage.error.noImagesFound": "Non sono state trovate immagini in questa pagina.",
        "webimage.error.schemeNotAllowed": "Questo schema URL non è consentito.",
        "webimage.error.httpNotAllowed": "Questo URL usa HTTP. È consentito solo HTTPS. Cambia l'URL in HTTPS o chiedi allo sviluppatore di consentire HTTP.",
        "webimage.skippedHTTPImagesNoticeFormat": "Alcune immagini sono state saltate perché usano HTTP (%lld). Usa URL HTTPS o chiedi allo sviluppatore di consentire HTTP.",
        "webimage.loadPage": "Carica pagina",
        "webimage.loading": "Caricamento",
        "webimage.navTitle": "Immagini web",
        "webimage.selectionSummaryFormat": "%1$lld di %2$lld selezionate",
        "webimage.urlEntryFooter": "Incolla un URL di pagina. Le immagini dalla risposta HTML vengono mostrate (le immagini solo JavaScript potrebbero mancare).",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Pagine aggiuntive",
        "webimage.additionalPagesFooter": "Opzionale: aggiungi altri URL di pagine per combinare immagini da più pagine.",
        "webimage.addPage": "Aggiungi pagina",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Impossibile caricare immagini da nessuna delle pagine.",
        "webimage.partialPageFailuresFormat": "%lld pagina/e non ha potuto essere caricata. Le immagini delle altre pagine vengono mostrate.",
        "webimage.searchPlaceholder": "Cerca per alt, titolo o URL",
    },
    "ru": {
        "webimage.a11y.imageFromWeb": "Изображение из интернета",
        "webimage.a11y.selectionSummaryFormat": "Выбрано %1$lld из %2$lld",
        "webimage.a11y.imageSearchField": "Поиск изображений",
        "webimage.a11y.imageSearchFieldHint": "Фильтрует список по alt-тексту, заголовку или адресу изображения. Добавьте format:png или format:webp для фильтрации по типу файла.",
        "webimage.cancel": "Отмена",
        "webimage.changeURL": "Изменить URL",
        "webimage.done": "Готово",
        "webimage.error.downloadFailed": "Не удалось загрузить изображение.",
        "webimage.error.unsupportedImageType": "Этот тип изображения не разрешён.",
        "webimage.error.imageDecodeFailed": "Загруженные данные не удалось декодировать как изображение.",
        "webimage.error.enterValidURL": "Введите допустимый URL.",
        "webimage.error.extractionFailed": "Не удалось прочитать изображения с этой страницы.",
        "webimage.error.generic": "Что-то пошло не так.",
        "webimage.error.htmlDecodingFailed": "Не удалось прочитать текст страницы.",
        "webimage.error.htmlTooLarge": "Страница слишком большая для безопасной загрузки.",
        "webimage.error.imageTooLarge": "Изображение было слишком большим для загрузки.",
        "webimage.error.invalidHTTPResponse": "Сервер не вернул страницу.",
        "webimage.error.invalidURL": "Этот URL не разрешён или недействителен.",
        "webimage.error.noImagesFound": "На этой странице не найдено изображений.",
        "webimage.error.schemeNotAllowed": "Эта схема URL не разрешена.",
        "webimage.error.httpNotAllowed": "Этот URL использует HTTP. Разрешён только HTTPS. Измените URL на HTTPS или попросите разработчика приложения разрешить HTTP.",
        "webimage.skippedHTTPImagesNoticeFormat": "Некоторые изображения были пропущены, так как используют HTTP (%lld). Используйте HTTPS-адреса изображений или попросите разработчика разрешить HTTP.",
        "webimage.loadPage": "Загрузить страницу",
        "webimage.loading": "Загрузка",
        "webimage.navTitle": "Веб-изображения",
        "webimage.selectionSummaryFormat": "Выбрано %1$lld из %2$lld",
        "webimage.urlEntryFooter": "Вставьте URL страницы. Отображаются изображения из HTML-ответа (изображения только на JavaScript могут отсутствовать).",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Дополнительные страницы",
        "webimage.additionalPagesFooter": "Необязательно: добавьте ещё URL-адреса страниц для объединения изображений с нескольких страниц.",
        "webimage.addPage": "Добавить страницу",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Не удалось загрузить изображения ни с одной страницы.",
        "webimage.partialPageFailuresFormat": "%lld страниц(ы) не удалось загрузить. Отображаются изображения с других страниц.",
        "webimage.searchPlaceholder": "Поиск по alt, заголовку или URL",
    },
}

# Locales that use English as-is (regional English variants)
EN_REGION_LOCALES = ["en-AU", "en-CA", "en-GB", "en-IN"]

# Generate all other locales from existing Spanish translation + provide distinct ones for major languages
# For all remaining locales not fully translated, generate from English with a note
# Full list of all target locales (excluding en, es which already exist)
ALL_TARGET_LOCALES = [
    "af","ar","be","bg","bn","ca","cs","cy","da","de","el",
    "en-AU","en-CA","en-GB","en-IN",
    "es-419","es-US","et","eu","fa","fi","fil",
    "fr","fr-CA","ga","gl","he","hi","hr","hu","hy",
    "id","is","it","ja","ka","kk","ko","lt","lv","mk","mn","ms",
    "nb","nl","pl","pt-BR","pt-PT","ro","ru","sk","sl","sq",
    "sr","sr-Latn","sv","sw","ta","te","th","tr","uk","ur","uz",
    "vi","zh-HK","zh-Hans","zh-Hant"
]

# Build per-locale translation dicts for locales not fully defined above
# Use regional English for en-* variants, and build other locales from patterns

def build_locale_strings(locale):
    """Return strings dict for a locale, falling back to English for untranslated."""
    # Use provided full translations if available
    if locale in TRANSLATIONS:
        return TRANSLATIONS[locale]

    # English regional variants
    if locale in EN_REGION_LOCALES:
        t = dict(EN_STRINGS)
        if locale in ("en-AU", "en-CA", "en-GB", "en-IN"):
            # Use British spelling for colour in en-GB, en-AU; otherwise same as en
            pass
        return t

    # For es-419 and es-US, use Spanish
    if locale in ("es-419", "es-US"):
        # Read from es translations defined inline
        es_t = {
            "webimage.a11y.imageFromWeb": "Imagen de la web",
            "webimage.a11y.selectionSummaryFormat": "%1$lld de %2$lld seleccionadas",
            "webimage.a11y.imageSearchField": "Buscar imágenes",
            "webimage.a11y.imageSearchFieldHint": "Filtra la lista por texto alternativo, título o dirección de la imagen. Añade format:png o format:webp para acotar por tipo de archivo.",
            "webimage.cancel": "Cancelar",
            "webimage.changeURL": "Cambiar URL",
            "webimage.done": "Listo",
            "webimage.error.downloadFailed": "No se pudo descargar una imagen.",
            "webimage.error.unsupportedImageType": "Este tipo de imagen no está permitido.",
            "webimage.error.imageDecodeFailed": "Los datos descargados no se pudieron decodificar como imagen.",
            "webimage.error.enterValidURL": "Introduce una URL válida.",
            "webimage.error.extractionFailed": "No se pudieron leer las imágenes de esta página.",
            "webimage.error.generic": "Algo salió mal.",
            "webimage.error.htmlDecodingFailed": "No se pudo leer el texto de la página.",
            "webimage.error.htmlTooLarge": "La página es demasiado grande para cargarla con seguridad.",
            "webimage.error.imageTooLarge": "Una imagen era demasiado grande para descargarla.",
            "webimage.error.invalidHTTPResponse": "El servidor no devolvió la página.",
            "webimage.error.invalidURL": "Esa URL no está permitida o no es válida.",
            "webimage.error.noImagesFound": "No se encontraron imágenes en esta página.",
            "webimage.error.schemeNotAllowed": "Este esquema de URL no está permitido.",
            "webimage.error.httpNotAllowed": "Esta URL usa HTTP. Solo se permite HTTPS. Cambia la URL a HTTPS o pide al desarrollador que permita HTTP.",
            "webimage.skippedHTTPImagesNoticeFormat": "Se omitieron algunas imágenes porque usan HTTP (%lld). Usa URLs de imagen HTTPS o pide al desarrollador que permita HTTP.",
            "webimage.loadPage": "Cargar página",
            "webimage.loading": "Cargando",
            "webimage.navTitle": "Imágenes web",
            "webimage.selectionSummaryFormat": "%1$lld de %2$lld seleccionadas",
            "webimage.urlEntryFooter": "Pega la URL de una página. Se muestran las imágenes de la respuesta HTML.",
            "webimage.urlPlaceholder": "https://example.com",
            "webimage.additionalPagesSection": "Páginas adicionales",
            "webimage.additionalPagesFooter": "Opcional: añade más URLs de página para combinar imágenes de varias páginas.",
            "webimage.addPage": "Añadir página",
            "webimage.extraPagePlaceholder": "https://another.example.com",
            "webimage.error.allPagesFailed": "No se pudieron cargar imágenes de ninguna de las páginas.",
            "webimage.partialPageFailuresFormat": "No se pudieron cargar %lld página(s). Se muestran imágenes de las demás.",
            "webimage.searchPlaceholder": "Buscar por texto alt, título o URL",
        }
        return es_t

    # fr-CA: same as fr
    if locale == "fr-CA":
        return TRANSLATIONS["fr"]

    # pt-PT: very close to pt-BR
    if locale == "pt-PT":
        t = dict(TRANSLATIONS["pt-BR"])
        t["webimage.done"] = "Concluído"
        t["webimage.loadPage"] = "Carregar página"
        t["webimage.loading"] = "A carregar"
        t["webimage.navTitle"] = "Imagens web"
        t["webimage.addPage"] = "Adicionar página"
        t["webimage.searchPlaceholder"] = "Pesquisar por alt, título ou URL"
        return t

    # sr-Latn: latin script version of Serbian
    if locale == "sr-Latn":
        sr_t = {
            "webimage.a11y.imageFromWeb": "Slika sa weba",
            "webimage.a11y.selectionSummaryFormat": "%1$lld od %2$lld odabrano",
            "webimage.a11y.imageSearchField": "Pretraži slike",
            "webimage.a11y.imageSearchFieldHint": "Filtrira listu po alt tekstu, naslovu ili adresi slike. Dodajte format:png ili format:webp za filtriranje po tipu fajla.",
            "webimage.cancel": "Otkaži",
            "webimage.changeURL": "Promeni URL",
            "webimage.done": "Gotovo",
            "webimage.error.downloadFailed": "Nije moguće preuzeti sliku.",
            "webimage.error.unsupportedImageType": "Ovaj tip slike nije dozvoljen.",
            "webimage.error.imageDecodeFailed": "Preuzeti podaci ne mogu biti dekodirani kao slika.",
            "webimage.error.enterValidURL": "Unesite validan URL.",
            "webimage.error.extractionFailed": "Nije moguće pročitati slike sa ove stranice.",
            "webimage.error.generic": "Nešto je pošlo po zlu.",
            "webimage.error.htmlDecodingFailed": "Nije moguće pročitati tekst stranice.",
            "webimage.error.htmlTooLarge": "Stranica je prevelika da bi se bezbedno učitala.",
            "webimage.error.imageTooLarge": "Slika je bila prevelika za preuzimanje.",
            "webimage.error.invalidHTTPResponse": "Server nije vratio stranicu.",
            "webimage.error.invalidURL": "Taj URL nije dozvoljen ili je nevažeći.",
            "webimage.error.noImagesFound": "Na ovoj stranici nisu pronađene slike.",
            "webimage.error.schemeNotAllowed": "Ovaj URL šema nije dozvoljen.",
            "webimage.error.httpNotAllowed": "Ovaj URL koristi HTTP. Dozvoljen je samo HTTPS. Promenite URL na HTTPS ili zamolite programera da dozvoli HTTP.",
            "webimage.skippedHTTPImagesNoticeFormat": "Neke slike su preskočene jer koriste HTTP (%lld). Koristite HTTPS URL-ove ili zamolite programera.",
            "webimage.loadPage": "Učitaj stranicu",
            "webimage.loading": "Učitavanje",
            "webimage.navTitle": "Web slike",
            "webimage.selectionSummaryFormat": "%1$lld od %2$lld odabrano",
            "webimage.urlEntryFooter": "Nalepite URL stranice. Slike iz HTML odgovora su prikazane.",
            "webimage.urlPlaceholder": "https://example.com",
            "webimage.additionalPagesSection": "Dodatne stranice",
            "webimage.additionalPagesFooter": "Opcionalno: dodajte više URL-ova stranica za kombinovanje slika.",
            "webimage.addPage": "Dodaj stranicu",
            "webimage.extraPagePlaceholder": "https://another.example.com",
            "webimage.error.allPagesFailed": "Nije moguće učitati slike ni sa jedne stranice.",
            "webimage.partialPageFailuresFormat": "%lld stranica nije mogla biti učitana. Slike sa ostalih stranica su prikazane.",
            "webimage.searchPlaceholder": "Pretraži po alt, naslovu ili URL",
        }
        return sr_t

    # For all other locales, generate structured translations
    locale_data = LOCALE_TRANSLATIONS.get(locale)
    if locale_data:
        return locale_data

    # Fallback: use English
    return dict(EN_STRINGS)


# Pre-built translations for remaining locales
LOCALE_TRANSLATIONS = {
    "be": {
        "webimage.a11y.imageFromWeb": "Выява з інтэрнэту",
        "webimage.a11y.selectionSummaryFormat": "%1$lld з %2$lld выбрана",
        "webimage.a11y.imageSearchField": "Пошук выяваў",
        "webimage.a11y.imageSearchFieldHint": "Фільтруе спіс па alt-тэксту, загалоўку або адрасе выявы.",
        "webimage.cancel": "Скасаваць",
        "webimage.changeURL": "Змяніць URL",
        "webimage.done": "Гатова",
        "webimage.error.downloadFailed": "Не ўдалося спампаваць выяву.",
        "webimage.error.unsupportedImageType": "Гэты тып выявы не дазволены.",
        "webimage.error.imageDecodeFailed": "Спампаваныя даныя не ўдалося расшыфраваць як выяву.",
        "webimage.error.enterValidURL": "Увядзіце сапраўдны URL.",
        "webimage.error.extractionFailed": "Не ўдалося прачытаць выявы з гэтай старонкі.",
        "webimage.error.generic": "Нешта пайшло не так.",
        "webimage.error.htmlDecodingFailed": "Не ўдалося прачытаць тэкст старонкі.",
        "webimage.error.htmlTooLarge": "Старонка занадта вялікая для бяспечнай загрузкі.",
        "webimage.error.imageTooLarge": "Выява была занадта вялікай для загрузкі.",
        "webimage.error.invalidHTTPResponse": "Сервер не вярнуў старонку.",
        "webimage.error.invalidURL": "Гэты URL не дазволены або недзейсны.",
        "webimage.error.noImagesFound": "На гэтай старонцы не знойдзена выяваў.",
        "webimage.error.schemeNotAllowed": "Гэтая схема URL не дазволена.",
        "webimage.error.httpNotAllowed": "Гэты URL выкарыстоўвае HTTP. Дазволены толькі HTTPS.",
        "webimage.skippedHTTPImagesNoticeFormat": "Некаторыя выявы прапушчаны, бо выкарыстоўваюць HTTP (%lld).",
        "webimage.loadPage": "Загрузіць старонку",
        "webimage.loading": "Загрузка",
        "webimage.navTitle": "Выявы з інтэрнэту",
        "webimage.selectionSummaryFormat": "%1$lld з %2$lld выбрана",
        "webimage.urlEntryFooter": "Устаўце URL старонкі. Адлюстроўваюцца выявы з HTML-адказу.",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Дадатковыя старонкі",
        "webimage.additionalPagesFooter": "Неабавязкова: дадайце больш URL старонак.",
        "webimage.addPage": "Дадаць старонку",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Не ўдалося загрузіць выявы ні з адной старонкі.",
        "webimage.partialPageFailuresFormat": "%lld старонак не ўдалося загрузіць. Паказваюцца выявы з іншых старонак.",
        "webimage.searchPlaceholder": "Пошук па alt, загалоўку або URL",
    },
    "bg": {
        "webimage.a11y.imageFromWeb": "Изображение от мрежата",
        "webimage.a11y.selectionSummaryFormat": "%1$lld от %2$lld избрани",
        "webimage.a11y.imageSearchField": "Търсене на изображения",
        "webimage.a11y.imageSearchFieldHint": "Филтрира списъка по alt текст, заглавие или адрес на изображение.",
        "webimage.cancel": "Отказ",
        "webimage.changeURL": "Промяна на URL",
        "webimage.done": "Готово",
        "webimage.error.downloadFailed": "Неуспешно изтегляне на изображение.",
        "webimage.error.unsupportedImageType": "Този тип изображение не е разрешен.",
        "webimage.error.imageDecodeFailed": "Изтеглените данни не могат да бъдат декодирани като изображение.",
        "webimage.error.enterValidURL": "Въведете валиден URL.",
        "webimage.error.extractionFailed": "Неуспешно четене на изображения от тази страница.",
        "webimage.error.generic": "Нещо се обърка.",
        "webimage.error.htmlDecodingFailed": "Неуспешно четене на текста на страницата.",
        "webimage.error.htmlTooLarge": "Страницата е твърде голяма за безопасно зареждане.",
        "webimage.error.imageTooLarge": "Изображението беше твърде голямо за изтегляне.",
        "webimage.error.invalidHTTPResponse": "Сървърът не върна страницата.",
        "webimage.error.invalidURL": "Този URL не е разрешен или е невалиден.",
        "webimage.error.noImagesFound": "На тази страница не са намерени изображения.",
        "webimage.error.schemeNotAllowed": "Тази URL схема не е разрешена.",
        "webimage.error.httpNotAllowed": "Този URL използва HTTP. Разрешен е само HTTPS.",
        "webimage.skippedHTTPImagesNoticeFormat": "Пропуснати са %lld изображения, защото използват HTTP.",
        "webimage.loadPage": "Зареди страница",
        "webimage.loading": "Зарежда се",
        "webimage.navTitle": "Уеб изображения",
        "webimage.selectionSummaryFormat": "%1$lld от %2$lld избрани",
        "webimage.urlEntryFooter": "Поставете URL на страница. Показват се изображения от HTML отговора.",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Допълнителни страници",
        "webimage.additionalPagesFooter": "По избор: добавете повече URL адреси на страници.",
        "webimage.addPage": "Добави страница",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Неуспешно зареждане на изображения от всяка страница.",
        "webimage.partialPageFailuresFormat": "%lld страница(и) не можаха да се заредят. Показват се изображения от другите.",
        "webimage.searchPlaceholder": "Търсене по alt, заглавие или URL",
    },
    "tr": {
        "webimage.a11y.imageFromWeb": "Web'den resim",
        "webimage.a11y.selectionSummaryFormat": "%2$lld'den %1$lld seçildi",
        "webimage.a11y.imageSearchField": "Resim ara",
        "webimage.a11y.imageSearchFieldHint": "Listeyi alt metni, başlık veya resim adresine göre filtreler. Dosya türüne göre daraltmak için format:png veya format:webp ekleyin.",
        "webimage.cancel": "İptal",
        "webimage.changeURL": "URL'yi Değiştir",
        "webimage.done": "Tamam",
        "webimage.error.downloadFailed": "Bir resim indirilemedi.",
        "webimage.error.unsupportedImageType": "Bu resim türüne izin verilmiyor.",
        "webimage.error.imageDecodeFailed": "İndirilen veriler resim olarak çözümlenemedi.",
        "webimage.error.enterValidURL": "Geçerli bir URL girin.",
        "webimage.error.extractionFailed": "Bu sayfadan resimler okunamadı.",
        "webimage.error.generic": "Bir şeyler yanlış gitti.",
        "webimage.error.htmlDecodingFailed": "Sayfa metni okunamadı.",
        "webimage.error.htmlTooLarge": "Sayfa güvenli şekilde yüklenemeyecek kadar büyük.",
        "webimage.error.imageTooLarge": "Bir resim indirilemeyecek kadar büyüktü.",
        "webimage.error.invalidHTTPResponse": "Sunucu sayfayı döndürmedi.",
        "webimage.error.invalidURL": "Bu URL'ye izin verilmiyor veya geçersiz.",
        "webimage.error.noImagesFound": "Bu sayfada resim bulunamadı.",
        "webimage.error.schemeNotAllowed": "Bu URL şemasına izin verilmiyor.",
        "webimage.error.httpNotAllowed": "Bu URL HTTP kullanıyor. Yalnızca HTTPS'ye izin var. URL'yi HTTPS olarak değiştirin veya geliştiriciden HTTP'ye izin vermesini isteyin.",
        "webimage.skippedHTTPImagesNoticeFormat": "HTTP kullanan %lld resim atlandı. HTTPS resim URL'leri kullanın.",
        "webimage.loadPage": "Sayfa yükle",
        "webimage.loading": "Yükleniyor",
        "webimage.navTitle": "Web resimleri",
        "webimage.selectionSummaryFormat": "%2$lld'den %1$lld seçildi",
        "webimage.urlEntryFooter": "Bir sayfa URL'si yapıştırın. HTML yanıtından resimler gösterilir.",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Ek sayfalar",
        "webimage.additionalPagesFooter": "İsteğe bağlı: birden fazla sayfadan resimleri birleştirmek için URL ekleyin.",
        "webimage.addPage": "Sayfa ekle",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Hiçbir sayfadan resim yüklenemedi.",
        "webimage.partialPageFailuresFormat": "%lld sayfa yüklenemedi. Diğer sayfaların resimleri gösterilmektedir.",
        "webimage.searchPlaceholder": "Alt metin, başlık veya URL ile ara",
    },
    "hi": {
        "webimage.a11y.imageFromWeb": "वेब से छवि",
        "webimage.a11y.selectionSummaryFormat": "%2$lld में से %1$lld चुनी गई",
        "webimage.a11y.imageSearchField": "छवि खोजें",
        "webimage.a11y.imageSearchFieldHint": "alt टेक्स्ट, शीर्षक या छवि पते से सूची फ़िल्टर करता है।",
        "webimage.cancel": "रद्द करें",
        "webimage.changeURL": "URL बदलें",
        "webimage.done": "पूर्ण",
        "webimage.error.downloadFailed": "छवि डाउनलोड नहीं हो सकी।",
        "webimage.error.unsupportedImageType": "यह छवि प्रकार अनुमत नहीं है।",
        "webimage.error.imageDecodeFailed": "डाउनलोड किया गया डेटा छवि के रूप में डीकोड नहीं हो सका।",
        "webimage.error.enterValidURL": "एक वैध URL दर्ज करें।",
        "webimage.error.extractionFailed": "इस पृष्ठ से छवियाँ नहीं पढ़ी जा सकीं।",
        "webimage.error.generic": "कुछ गलत हो गया।",
        "webimage.error.htmlDecodingFailed": "पृष्ठ टेक्स्ट नहीं पढ़ा जा सका।",
        "webimage.error.htmlTooLarge": "पृष्ठ सुरक्षित रूप से लोड करने के लिए बहुत बड़ा है।",
        "webimage.error.imageTooLarge": "छवि डाउनलोड करने के लिए बहुत बड़ी थी।",
        "webimage.error.invalidHTTPResponse": "सर्वर ने पृष्ठ वापस नहीं किया।",
        "webimage.error.invalidURL": "यह URL अनुमत नहीं है या अमान्य है।",
        "webimage.error.noImagesFound": "इस पृष्ठ पर कोई छवि नहीं मिली।",
        "webimage.error.schemeNotAllowed": "यह URL स्कीम अनुमत नहीं है।",
        "webimage.error.httpNotAllowed": "यह URL HTTP का उपयोग करता है। केवल HTTPS अनुमत है।",
        "webimage.skippedHTTPImagesNoticeFormat": "कुछ छवियाँ छोड़ी गईं क्योंकि वे HTTP उपयोग करती हैं (%lld)।",
        "webimage.loadPage": "पृष्ठ लोड करें",
        "webimage.loading": "लोड हो रहा है",
        "webimage.navTitle": "वेब छवियाँ",
        "webimage.selectionSummaryFormat": "%2$lld में से %1$lld चुनी गई",
        "webimage.urlEntryFooter": "एक पृष्ठ URL पेस्ट करें। HTML प्रतिक्रिया की छवियाँ दिखाई जाती हैं।",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "अतिरिक्त पृष्ठ",
        "webimage.additionalPagesFooter": "वैकल्पिक: कई पृष्ठों से छवियाँ जोड़ने के लिए और URL जोड़ें।",
        "webimage.addPage": "पृष्ठ जोड़ें",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "किसी भी पृष्ठ से छवियाँ लोड नहीं हो सकीं।",
        "webimage.partialPageFailuresFormat": "%lld पृष्ठ लोड नहीं हो सके। अन्य पृष्ठों की छवियाँ दिखाई जा रही हैं।",
        "webimage.searchPlaceholder": "alt, शीर्षक या URL से खोजें",
    },
    "nl": {
        "webimage.a11y.imageFromWeb": "Afbeelding van het web",
        "webimage.a11y.selectionSummaryFormat": "%1$lld van %2$lld geselecteerd",
        "webimage.a11y.imageSearchField": "Afbeeldingen zoeken",
        "webimage.a11y.imageSearchFieldHint": "Filtert de lijst op alt-tekst, titel of afbeeldingsadres.",
        "webimage.cancel": "Annuleer",
        "webimage.changeURL": "URL wijzigen",
        "webimage.done": "Klaar",
        "webimage.error.downloadFailed": "Kon een afbeelding niet downloaden.",
        "webimage.error.unsupportedImageType": "Dit afbeeldingstype is niet toegestaan.",
        "webimage.error.imageDecodeFailed": "Gedownloade data kon niet worden gedecodeerd als afbeelding.",
        "webimage.error.enterValidURL": "Voer een geldige URL in.",
        "webimage.error.extractionFailed": "Kon geen afbeeldingen van deze pagina lezen.",
        "webimage.error.generic": "Er is iets misgegaan.",
        "webimage.error.htmlDecodingFailed": "Kon de paginatekst niet lezen.",
        "webimage.error.htmlTooLarge": "De pagina is te groot om veilig te laden.",
        "webimage.error.imageTooLarge": "Een afbeelding was te groot om te downloaden.",
        "webimage.error.invalidHTTPResponse": "De server heeft de pagina niet geretourneerd.",
        "webimage.error.invalidURL": "Die URL is niet toegestaan of ongeldig.",
        "webimage.error.noImagesFound": "Er zijn geen afbeeldingen gevonden op deze pagina.",
        "webimage.error.schemeNotAllowed": "Dit URL-schema is niet toegestaan.",
        "webimage.error.httpNotAllowed": "Deze URL gebruikt HTTP. Alleen HTTPS is toegestaan.",
        "webimage.skippedHTTPImagesNoticeFormat": "Sommige afbeeldingen zijn overgeslagen omdat ze HTTP gebruiken (%lld).",
        "webimage.loadPage": "Pagina laden",
        "webimage.loading": "Laden",
        "webimage.navTitle": "Webafbeeldingen",
        "webimage.selectionSummaryFormat": "%1$lld van %2$lld geselecteerd",
        "webimage.urlEntryFooter": "Plak een pagina-URL. Afbeeldingen uit de HTML-reactie worden weergegeven.",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Extra pagina's",
        "webimage.additionalPagesFooter": "Optioneel: voeg meer pagina-URL's toe om afbeeldingen samen te voegen.",
        "webimage.addPage": "Pagina toevoegen",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Kon geen afbeeldingen laden van een van de pagina's.",
        "webimage.partialPageFailuresFormat": "%lld pagina('s) kon(den) niet worden geladen. Afbeeldingen van andere pagina's worden weergegeven.",
        "webimage.searchPlaceholder": "Zoeken op alt, titel of URL",
    },
    "pl": {
        "webimage.a11y.imageFromWeb": "Obraz z sieci",
        "webimage.a11y.selectionSummaryFormat": "%1$lld z %2$lld wybranych",
        "webimage.a11y.imageSearchField": "Szukaj obrazów",
        "webimage.a11y.imageSearchFieldHint": "Filtruje listę według tekstu alt, tytułu lub adresu obrazu.",
        "webimage.cancel": "Anuluj",
        "webimage.changeURL": "Zmień URL",
        "webimage.done": "Gotowe",
        "webimage.error.downloadFailed": "Nie można pobrać obrazu.",
        "webimage.error.unsupportedImageType": "Ten typ obrazu nie jest dozwolony.",
        "webimage.error.imageDecodeFailed": "Pobrane dane nie mogły być zdekodowane jako obraz.",
        "webimage.error.enterValidURL": "Wpisz prawidłowy URL.",
        "webimage.error.extractionFailed": "Nie można odczytać obrazów z tej strony.",
        "webimage.error.generic": "Coś poszło nie tak.",
        "webimage.error.htmlDecodingFailed": "Nie można odczytać tekstu strony.",
        "webimage.error.htmlTooLarge": "Strona jest zbyt duża, aby bezpiecznie ją załadować.",
        "webimage.error.imageTooLarge": "Obraz był zbyt duży do pobrania.",
        "webimage.error.invalidHTTPResponse": "Serwer nie zwrócił strony.",
        "webimage.error.invalidURL": "Ten URL nie jest dozwolony lub jest nieprawidłowy.",
        "webimage.error.noImagesFound": "Nie znaleziono obrazów na tej stronie.",
        "webimage.error.schemeNotAllowed": "Ten schemat URL nie jest dozwolony.",
        "webimage.error.httpNotAllowed": "Ten URL używa HTTP. Dozwolony jest tylko HTTPS.",
        "webimage.skippedHTTPImagesNoticeFormat": "Pominięto %lld obrazów używających HTTP.",
        "webimage.loadPage": "Załaduj stronę",
        "webimage.loading": "Ładowanie",
        "webimage.navTitle": "Obrazy z sieci",
        "webimage.selectionSummaryFormat": "%1$lld z %2$lld wybranych",
        "webimage.urlEntryFooter": "Wklej adres URL strony. Wyświetlane są obrazy z odpowiedzi HTML.",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Dodatkowe strony",
        "webimage.additionalPagesFooter": "Opcjonalnie: dodaj więcej adresów URL stron.",
        "webimage.addPage": "Dodaj stronę",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Nie można załadować obrazów z żadnej strony.",
        "webimage.partialPageFailuresFormat": "%lld stron(y) nie mogło zostać załadowanych. Wyświetlane są obrazy z pozostałych.",
        "webimage.searchPlaceholder": "Szukaj po alt, tytule lub URL",
    },
    "sv": {
        "webimage.a11y.imageFromWeb": "Bild från webben",
        "webimage.a11y.selectionSummaryFormat": "%1$lld av %2$lld valda",
        "webimage.a11y.imageSearchField": "Sök bilder",
        "webimage.a11y.imageSearchFieldHint": "Filtrerar listan efter alt-text, titel eller bildadress.",
        "webimage.cancel": "Avbryt",
        "webimage.changeURL": "Ändra URL",
        "webimage.done": "Klar",
        "webimage.error.downloadFailed": "Kunde inte hämta en bild.",
        "webimage.error.unsupportedImageType": "Den här bildtypen är inte tillåten.",
        "webimage.error.imageDecodeFailed": "Hämtad data kunde inte avkodas som bild.",
        "webimage.error.enterValidURL": "Ange en giltig URL.",
        "webimage.error.extractionFailed": "Kunde inte läsa bilder från den här sidan.",
        "webimage.error.generic": "Något gick fel.",
        "webimage.error.htmlDecodingFailed": "Kunde inte läsa sidtexten.",
        "webimage.error.htmlTooLarge": "Sidan är för stor för att läsas in säkert.",
        "webimage.error.imageTooLarge": "En bild var för stor för att hämtas.",
        "webimage.error.invalidHTTPResponse": "Servern returnerade inte sidan.",
        "webimage.error.invalidURL": "Den URL:en är inte tillåten eller ogiltig.",
        "webimage.error.noImagesFound": "Inga bilder hittades på den här sidan.",
        "webimage.error.schemeNotAllowed": "Det här URL-schemat är inte tillåtet.",
        "webimage.error.httpNotAllowed": "Den här URL:en använder HTTP. Bara HTTPS är tillåtet.",
        "webimage.skippedHTTPImagesNoticeFormat": "Vissa bilder hoppades över eftersom de använder HTTP (%lld).",
        "webimage.loadPage": "Ladda sida",
        "webimage.loading": "Laddar",
        "webimage.navTitle": "Webbbilder",
        "webimage.selectionSummaryFormat": "%1$lld av %2$lld valda",
        "webimage.urlEntryFooter": "Klistra in en sidadress. Bilder från HTML-svaret visas.",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Extra sidor",
        "webimage.additionalPagesFooter": "Valfritt: lägg till fler sidadresser för att kombinera bilder.",
        "webimage.addPage": "Lägg till sida",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Kunde inte ladda bilder från någon av sidorna.",
        "webimage.partialPageFailuresFormat": "%lld sida/sidor kunde inte laddas. Bilder från övriga visas.",
        "webimage.searchPlaceholder": "Sök efter alt, titel eller URL",
    },
    "da": {
        "webimage.a11y.imageFromWeb": "Billede fra nettet",
        "webimage.a11y.selectionSummaryFormat": "%1$lld af %2$lld valgt",
        "webimage.a11y.imageSearchField": "Søg billeder",
        "webimage.a11y.imageSearchFieldHint": "Filtrerer listen efter alt-tekst, titel eller billedadresse.",
        "webimage.cancel": "Annuller",
        "webimage.changeURL": "Skift URL",
        "webimage.done": "Udført",
        "webimage.error.downloadFailed": "Kunne ikke hente et billede.",
        "webimage.error.unsupportedImageType": "Denne billedtype er ikke tilladt.",
        "webimage.error.imageDecodeFailed": "Downloadede data kunne ikke afkodes som billede.",
        "webimage.error.enterValidURL": "Indtast en gyldig URL.",
        "webimage.error.extractionFailed": "Kunne ikke læse billeder fra denne side.",
        "webimage.error.generic": "Noget gik galt.",
        "webimage.error.htmlDecodingFailed": "Kunne ikke læse sideteksten.",
        "webimage.error.htmlTooLarge": "Siden er for stor til at indlæse sikkert.",
        "webimage.error.imageTooLarge": "Et billede var for stort til at downloade.",
        "webimage.error.invalidHTTPResponse": "Serveren returnerede ikke siden.",
        "webimage.error.invalidURL": "Den URL er ikke tilladt eller ugyldig.",
        "webimage.error.noImagesFound": "Der blev ikke fundet billeder på denne side.",
        "webimage.error.schemeNotAllowed": "Dette URL-skema er ikke tilladt.",
        "webimage.error.httpNotAllowed": "Denne URL bruger HTTP. Kun HTTPS er tilladt.",
        "webimage.skippedHTTPImagesNoticeFormat": "Nogle billeder blev sprunget over, fordi de bruger HTTP (%lld).",
        "webimage.loadPage": "Indlæs side",
        "webimage.loading": "Indlæser",
        "webimage.navTitle": "Webbilleder",
        "webimage.selectionSummaryFormat": "%1$lld af %2$lld valgt",
        "webimage.urlEntryFooter": "Indsæt en side-URL. Billeder fra HTML-svaret vises.",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Yderligere sider",
        "webimage.additionalPagesFooter": "Valgfrit: tilføj flere side-URL'er for at kombinere billeder.",
        "webimage.addPage": "Tilføj side",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Kunne ikke indlæse billeder fra nogen af siderne.",
        "webimage.partialPageFailuresFormat": "%lld side(r) kunne ikke indlæses. Billeder fra de andre vises.",
        "webimage.searchPlaceholder": "Søg efter alt, titel eller URL",
    },
    "nb": {
        "webimage.a11y.imageFromWeb": "Bilde fra nettet",
        "webimage.a11y.selectionSummaryFormat": "%1$lld av %2$lld valgt",
        "webimage.a11y.imageSearchField": "Søk bilder",
        "webimage.a11y.imageSearchFieldHint": "Filtrerer listen etter alt-tekst, tittel eller bildeadresse.",
        "webimage.cancel": "Avbryt",
        "webimage.changeURL": "Endre URL",
        "webimage.done": "Ferdig",
        "webimage.error.downloadFailed": "Kunne ikke laste ned et bilde.",
        "webimage.error.unsupportedImageType": "Denne bildetypen er ikke tillatt.",
        "webimage.error.imageDecodeFailed": "Nedlastede data kunne ikke dekodes som bilde.",
        "webimage.error.enterValidURL": "Skriv inn en gyldig URL.",
        "webimage.error.extractionFailed": "Kunne ikke lese bilder fra denne siden.",
        "webimage.error.generic": "Noe gikk galt.",
        "webimage.error.htmlDecodingFailed": "Kunne ikke lese sideteksten.",
        "webimage.error.htmlTooLarge": "Siden er for stor til å lastes inn trygt.",
        "webimage.error.imageTooLarge": "Et bilde var for stort til å lastes ned.",
        "webimage.error.invalidHTTPResponse": "Serveren returnerte ikke siden.",
        "webimage.error.invalidURL": "Den URL-en er ikke tillatt eller ugyldig.",
        "webimage.error.noImagesFound": "Ingen bilder ble funnet på denne siden.",
        "webimage.error.schemeNotAllowed": "Dette URL-skjemaet er ikke tillatt.",
        "webimage.error.httpNotAllowed": "Denne URL-en bruker HTTP. Bare HTTPS er tillatt.",
        "webimage.skippedHTTPImagesNoticeFormat": "Noen bilder ble hoppet over fordi de bruker HTTP (%lld).",
        "webimage.loadPage": "Last inn side",
        "webimage.loading": "Laster",
        "webimage.navTitle": "Nettbilder",
        "webimage.selectionSummaryFormat": "%1$lld av %2$lld valgt",
        "webimage.urlEntryFooter": "Lim inn en side-URL. Bilder fra HTML-svaret vises.",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Ekstra sider",
        "webimage.additionalPagesFooter": "Valgfritt: legg til flere side-URL-er for å kombinere bilder.",
        "webimage.addPage": "Legg til side",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Kunne ikke laste inn bilder fra noen av sidene.",
        "webimage.partialPageFailuresFormat": "%lld side(r) kunne ikke lastes inn. Bilder fra de andre vises.",
        "webimage.searchPlaceholder": "Søk etter alt, tittel eller URL",
    },
    "fi": {
        "webimage.a11y.imageFromWeb": "Kuva verkosta",
        "webimage.a11y.selectionSummaryFormat": "%1$lld / %2$lld valittu",
        "webimage.a11y.imageSearchField": "Hae kuvia",
        "webimage.a11y.imageSearchFieldHint": "Suodattaa luettelon alt-tekstin, otsikon tai kuvan osoitteen mukaan.",
        "webimage.cancel": "Peruuta",
        "webimage.changeURL": "Muuta URL",
        "webimage.done": "Valmis",
        "webimage.error.downloadFailed": "Kuvan lataaminen epäonnistui.",
        "webimage.error.unsupportedImageType": "Tämä kuvatyyppi ei ole sallittu.",
        "webimage.error.imageDecodeFailed": "Ladattuja tietoja ei voitu purkaa kuvaksi.",
        "webimage.error.enterValidURL": "Kirjoita kelvollinen URL.",
        "webimage.error.extractionFailed": "Kuvia ei voitu lukea tältä sivulta.",
        "webimage.error.generic": "Jokin meni pieleen.",
        "webimage.error.htmlDecodingFailed": "Sivun tekstiä ei voitu lukea.",
        "webimage.error.htmlTooLarge": "Sivu on liian suuri ladattavaksi turvallisesti.",
        "webimage.error.imageTooLarge": "Kuva oli liian suuri ladattavaksi.",
        "webimage.error.invalidHTTPResponse": "Palvelin ei palauttanut sivua.",
        "webimage.error.invalidURL": "Tätä URL-osoitetta ei sallita tai se on virheellinen.",
        "webimage.error.noImagesFound": "Tältä sivulta ei löytynyt kuvia.",
        "webimage.error.schemeNotAllowed": "Tätä URL-järjestelmää ei sallita.",
        "webimage.error.httpNotAllowed": "Tämä URL käyttää HTTP:tä. Vain HTTPS on sallittu.",
        "webimage.skippedHTTPImagesNoticeFormat": "Jotkut kuvat ohitettiin, koska ne käyttävät HTTP:tä (%lld).",
        "webimage.loadPage": "Lataa sivu",
        "webimage.loading": "Ladataan",
        "webimage.navTitle": "Verkossa olevat kuvat",
        "webimage.selectionSummaryFormat": "%1$lld / %2$lld valittu",
        "webimage.urlEntryFooter": "Liitä sivun URL-osoite. HTML-vastauksesta löydetyt kuvat näytetään.",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Lisäsivut",
        "webimage.additionalPagesFooter": "Valinnainen: lisää URL-osoitteita yhdistääksesi kuvia usealta sivulta.",
        "webimage.addPage": "Lisää sivu",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Kuvia ei voitu ladata yhdeltäkään sivulta.",
        "webimage.partialPageFailuresFormat": "%lld sivua ei voitu ladata. Muiden sivujen kuvat näytetään.",
        "webimage.searchPlaceholder": "Hae alt-tekstillä, otsikolla tai URL:lla",
    },
    "id": {
        "webimage.a11y.imageFromWeb": "Gambar dari web",
        "webimage.a11y.selectionSummaryFormat": "%1$lld dari %2$lld dipilih",
        "webimage.a11y.imageSearchField": "Cari gambar",
        "webimage.a11y.imageSearchFieldHint": "Memfilter daftar berdasarkan teks alt, judul, atau alamat gambar.",
        "webimage.cancel": "Batal",
        "webimage.changeURL": "Ubah URL",
        "webimage.done": "Selesai",
        "webimage.error.downloadFailed": "Tidak dapat mengunduh gambar.",
        "webimage.error.unsupportedImageType": "Jenis gambar ini tidak diizinkan.",
        "webimage.error.imageDecodeFailed": "Data yang diunduh tidak dapat didekode sebagai gambar.",
        "webimage.error.enterValidURL": "Masukkan URL yang valid.",
        "webimage.error.extractionFailed": "Tidak dapat membaca gambar dari halaman ini.",
        "webimage.error.generic": "Ada yang salah.",
        "webimage.error.htmlDecodingFailed": "Tidak dapat membaca teks halaman.",
        "webimage.error.htmlTooLarge": "Halaman terlalu besar untuk dimuat dengan aman.",
        "webimage.error.imageTooLarge": "Gambar terlalu besar untuk diunduh.",
        "webimage.error.invalidHTTPResponse": "Server tidak mengembalikan halaman.",
        "webimage.error.invalidURL": "URL tersebut tidak diizinkan atau tidak valid.",
        "webimage.error.noImagesFound": "Tidak ada gambar ditemukan di halaman ini.",
        "webimage.error.schemeNotAllowed": "Skema URL ini tidak diizinkan.",
        "webimage.error.httpNotAllowed": "URL ini menggunakan HTTP. Hanya HTTPS yang diizinkan.",
        "webimage.skippedHTTPImagesNoticeFormat": "Beberapa gambar dilewati karena menggunakan HTTP (%lld).",
        "webimage.loadPage": "Muat halaman",
        "webimage.loading": "Memuat",
        "webimage.navTitle": "Gambar web",
        "webimage.selectionSummaryFormat": "%1$lld dari %2$lld dipilih",
        "webimage.urlEntryFooter": "Tempel URL halaman. Gambar dari respons HTML ditampilkan.",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Halaman tambahan",
        "webimage.additionalPagesFooter": "Opsional: tambahkan lebih banyak URL halaman untuk menggabungkan gambar.",
        "webimage.addPage": "Tambah halaman",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Tidak dapat memuat gambar dari halaman mana pun.",
        "webimage.partialPageFailuresFormat": "%lld halaman tidak dapat dimuat. Gambar dari halaman lain ditampilkan.",
        "webimage.searchPlaceholder": "Cari berdasarkan alt, judul, atau URL",
    },
    "uk": {
        "webimage.a11y.imageFromWeb": "Зображення з мережі",
        "webimage.a11y.selectionSummaryFormat": "Вибрано %1$lld з %2$lld",
        "webimage.a11y.imageSearchField": "Пошук зображень",
        "webimage.a11y.imageSearchFieldHint": "Фільтрує список за alt-текстом, заголовком або адресою зображення.",
        "webimage.cancel": "Скасувати",
        "webimage.changeURL": "Змінити URL",
        "webimage.done": "Готово",
        "webimage.error.downloadFailed": "Не вдалося завантажити зображення.",
        "webimage.error.unsupportedImageType": "Цей тип зображення не дозволений.",
        "webimage.error.imageDecodeFailed": "Завантажені дані не вдалося декодувати як зображення.",
        "webimage.error.enterValidURL": "Введіть дійсний URL.",
        "webimage.error.extractionFailed": "Не вдалося прочитати зображення з цієї сторінки.",
        "webimage.error.generic": "Щось пішло не так.",
        "webimage.error.htmlDecodingFailed": "Не вдалося прочитати текст сторінки.",
        "webimage.error.htmlTooLarge": "Сторінка занадто велика для безпечного завантаження.",
        "webimage.error.imageTooLarge": "Зображення було занадто великим для завантаження.",
        "webimage.error.invalidHTTPResponse": "Сервер не повернув сторінку.",
        "webimage.error.invalidURL": "Цей URL не дозволений або недійсний.",
        "webimage.error.noImagesFound": "На цій сторінці не знайдено зображень.",
        "webimage.error.schemeNotAllowed": "Ця схема URL не дозволена.",
        "webimage.error.httpNotAllowed": "Цей URL використовує HTTP. Дозволено лише HTTPS.",
        "webimage.skippedHTTPImagesNoticeFormat": "Деякі зображення пропущено, оскільки вони використовують HTTP (%lld).",
        "webimage.loadPage": "Завантажити сторінку",
        "webimage.loading": "Завантаження",
        "webimage.navTitle": "Веб-зображення",
        "webimage.selectionSummaryFormat": "Вибрано %1$lld з %2$lld",
        "webimage.urlEntryFooter": "Вставте URL сторінки. Відображаються зображення з HTML-відповіді.",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Додаткові сторінки",
        "webimage.additionalPagesFooter": "Необов'язково: додайте більше URL-адрес сторінок.",
        "webimage.addPage": "Додати сторінку",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Не вдалося завантажити зображення з жодної сторінки.",
        "webimage.partialPageFailuresFormat": "%lld сторінок не вдалося завантажити. Зображення з інших сторінок відображаються.",
        "webimage.searchPlaceholder": "Пошук за alt, заголовком або URL",
    },
    "th": {
        "webimage.a11y.imageFromWeb": "รูปภาพจากเว็บ",
        "webimage.a11y.selectionSummaryFormat": "เลือก %1$lld จาก %2$lld รายการ",
        "webimage.a11y.imageSearchField": "ค้นหารูปภาพ",
        "webimage.a11y.imageSearchFieldHint": "กรองรายการด้วยข้อความ alt ชื่อ หรือที่อยู่รูปภาพ",
        "webimage.cancel": "ยกเลิก",
        "webimage.changeURL": "เปลี่ยน URL",
        "webimage.done": "เสร็จสิ้น",
        "webimage.error.downloadFailed": "ไม่สามารถดาวน์โหลดรูปภาพได้",
        "webimage.error.unsupportedImageType": "ประเภทรูปภาพนี้ไม่ได้รับอนุญาต",
        "webimage.error.imageDecodeFailed": "ไม่สามารถถอดรหัสข้อมูลที่ดาวน์โหลดเป็นรูปภาพได้",
        "webimage.error.enterValidURL": "กรอก URL ที่ถูกต้อง",
        "webimage.error.extractionFailed": "ไม่สามารถอ่านรูปภาพจากหน้านี้ได้",
        "webimage.error.generic": "เกิดข้อผิดพลาด",
        "webimage.error.htmlDecodingFailed": "ไม่สามารถอ่านข้อความในหน้าได้",
        "webimage.error.htmlTooLarge": "หน้าใหญ่เกินไปที่จะโหลดได้อย่างปลอดภัย",
        "webimage.error.imageTooLarge": "รูปภาพใหญ่เกินไปที่จะดาวน์โหลด",
        "webimage.error.invalidHTTPResponse": "เซิร์ฟเวอร์ไม่ได้ส่งคืนหน้า",
        "webimage.error.invalidURL": "URL นั้นไม่ได้รับอนุญาตหรือไม่ถูกต้อง",
        "webimage.error.noImagesFound": "ไม่พบรูปภาพในหน้านี้",
        "webimage.error.schemeNotAllowed": "ไม่อนุญาต URL scheme นี้",
        "webimage.error.httpNotAllowed": "URL นี้ใช้ HTTP อนุญาตเฉพาะ HTTPS เท่านั้น",
        "webimage.skippedHTTPImagesNoticeFormat": "ข้ามรูปภาพที่ใช้ HTTP จำนวน %lld รายการ",
        "webimage.loadPage": "โหลดหน้า",
        "webimage.loading": "กำลังโหลด",
        "webimage.navTitle": "รูปภาพจากเว็บ",
        "webimage.selectionSummaryFormat": "เลือก %1$lld จาก %2$lld รายการ",
        "webimage.urlEntryFooter": "วาง URL ของหน้า รูปภาพจากการตอบสนอง HTML จะแสดงขึ้น",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "หน้าเพิ่มเติม",
        "webimage.additionalPagesFooter": "ไม่บังคับ: เพิ่ม URL หน้าอื่นเพื่อรวมรูปภาพ",
        "webimage.addPage": "เพิ่มหน้า",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "ไม่สามารถโหลดรูปภาพจากหน้าใดเลย",
        "webimage.partialPageFailuresFormat": "ไม่สามารถโหลด %lld หน้าได้ แสดงรูปภาพจากหน้าอื่น",
        "webimage.searchPlaceholder": "ค้นหาด้วย alt ชื่อ หรือ URL",
    },
    "vi": {
        "webimage.a11y.imageFromWeb": "Ảnh từ web",
        "webimage.a11y.selectionSummaryFormat": "Đã chọn %1$lld trong số %2$lld",
        "webimage.a11y.imageSearchField": "Tìm kiếm ảnh",
        "webimage.a11y.imageSearchFieldHint": "Lọc danh sách theo văn bản alt, tiêu đề hoặc địa chỉ ảnh.",
        "webimage.cancel": "Hủy",
        "webimage.changeURL": "Thay đổi URL",
        "webimage.done": "Xong",
        "webimage.error.downloadFailed": "Không thể tải ảnh xuống.",
        "webimage.error.unsupportedImageType": "Loại ảnh này không được phép.",
        "webimage.error.imageDecodeFailed": "Dữ liệu tải về không thể giải mã thành ảnh.",
        "webimage.error.enterValidURL": "Nhập URL hợp lệ.",
        "webimage.error.extractionFailed": "Không thể đọc ảnh từ trang này.",
        "webimage.error.generic": "Đã xảy ra lỗi.",
        "webimage.error.htmlDecodingFailed": "Không thể đọc văn bản trang.",
        "webimage.error.htmlTooLarge": "Trang quá lớn để tải an toàn.",
        "webimage.error.imageTooLarge": "Ảnh quá lớn để tải xuống.",
        "webimage.error.invalidHTTPResponse": "Máy chủ không trả về trang.",
        "webimage.error.invalidURL": "URL đó không được phép hoặc không hợp lệ.",
        "webimage.error.noImagesFound": "Không tìm thấy ảnh nào trên trang này.",
        "webimage.error.schemeNotAllowed": "Sơ đồ URL này không được phép.",
        "webimage.error.httpNotAllowed": "URL này sử dụng HTTP. Chỉ cho phép HTTPS.",
        "webimage.skippedHTTPImagesNoticeFormat": "Một số ảnh đã bị bỏ qua vì dùng HTTP (%lld).",
        "webimage.loadPage": "Tải trang",
        "webimage.loading": "Đang tải",
        "webimage.navTitle": "Ảnh web",
        "webimage.selectionSummaryFormat": "Đã chọn %1$lld trong số %2$lld",
        "webimage.urlEntryFooter": "Dán URL trang. Ảnh từ phản hồi HTML được hiển thị.",
        "webimage.urlPlaceholder": "https://example.com",
        "webimage.additionalPagesSection": "Trang bổ sung",
        "webimage.additionalPagesFooter": "Tùy chọn: thêm URL trang khác để kết hợp ảnh.",
        "webimage.addPage": "Thêm trang",
        "webimage.extraPagePlaceholder": "https://another.example.com",
        "webimage.error.allPagesFailed": "Không thể tải ảnh từ bất kỳ trang nào.",
        "webimage.partialPageFailuresFormat": "%lld trang không thể tải. Ảnh từ các trang khác được hiển thị.",
        "webimage.searchPlaceholder": "Tìm theo alt, tiêu đề hoặc URL",
    },
}


def format_strings_file(strings_dict):
    """Format a .strings file from a dict."""
    lines = []
    for key, value in strings_dict.items():
        escaped_value = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'"{key}" = "{escaped_value}";')
    return "\n".join(lines) + "\n"


def main():
    existing = {"en", "es"}
    created = 0
    skipped = 0

    for locale in ALL_TARGET_LOCALES:
        lproj_dir = os.path.join(RESOURCES_DIR, f"{locale}.lproj")
        strings_path = os.path.join(lproj_dir, "Localizable.strings")

        if os.path.exists(strings_path):
            skipped += 1
            print(f"SKIP (exists): {locale}")
            continue

        strings = build_locale_strings(locale)
        os.makedirs(lproj_dir, exist_ok=True)

        with open(strings_path, "w", encoding="utf-8") as f:
            f.write(format_strings_file(strings))

        created += 1
        print(f"Created: {locale}")

    print(f"\nCreated {created} locale files, skipped {skipped}")


if __name__ == "__main__":
    main()
